export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';
export const GET_POST = 'GET_POST';
export const GET_POST_RESET = 'GET_POST_RESET';
export const GET_POST_FAIL = 'GET_POST_FAIL';
export const LIKE_POST = 'LIKE_POST';
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL';
export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';