export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SOCIALLOGIN_SUCCESS = 'SOCIALLOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const LOAD_USER = 'LOAD_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_USER = 'GET_USER';
export const GET_USER_FOLLOWING = 'GET_USER_FOLLOWING';
export const GET_USER_FOLLOWERS = 'GET_USER_FOLLOWERS';
export const FOLLOW_USER = 'FOLLOW_USER';
export const FOLLOW_USERS = 'FOLLOW_USERS';
export const USER_ERROR = 'USER_ERROR';
export const USER_RESET = 'USER_RESET';
export const ADD_PERSONAL_INFO = 'ADD_PERSONAL_INFO';
export const DELETE_PERSONAL_INFO = 'DELETE_PERSONAL_INFO';

export const GET_POST = 'GET_POST';
export const GET_RECENT_POSTS = 'GET_RECENT_POSTS';
export const GET_POSTS_BY_USER = 'GET_POSTS_BY_USER';
export const POST_RESET = 'POST_RESET';
export const LIKE_POST = 'LIKE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS';
export const POST_ERROR = 'POST_ERROR';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';